Integrated GDrive - save salon along with video file
Gospel-Crowd/salon-app pull request #32
Opened 2021-11-07 12:14 UTC by dragonfly91

2021-11-08 15:48 UTC, mazemaze requested changes
There's only one thing to fix, but otherwise Looks good to me

2021-11-08 15:48 UTC, mazemaze commented on salon_creator/lib/screens/gdrive_picker_screen.dart
> +        onPressed: () async {
```suggestion
        onPressed: () async {
```
onPressed is too long.

2021-11-11 13:50 UTC, dragonfly91 commented on salon_creator/lib/screens/gdrive_picker_screen.dart
> +        onPressed: () async {
modified, please check!

2021-11-15 12:41 UTC, mazemaze approved these changes
LGTM!

2021-11-16 09:58 UTC, merged

2021-11-20 10:53 UTC, Hiroki0613 reviewed
Minor content. About adding comments.

2021-11-20 10:53 UTC, Hiroki0613 commented on salon_creator/lib/main.dart
> +class MyHttpOverrides extends HttpOverrides {
It is better to put a comment. "Only use at develop"

2021-11-20 10:53 UTC, Hiroki0613 commented on salon_creator/lib/models/media_item.dart
> +class MediaItem {}
It is better to add a comment of structure.

2021-11-20 10:53 UTC, Hiroki0613 commented on salon_creator/lib/screens/gdrive_transfer_screen.dart
> +    setState(() {
There are two setState for operationInProgress but I think first 
・operationInProgress = true 
is countered by second
・operationInProgress = false